#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$install_dir"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/logrotate.d/$app"

ynh_backup "/etc/systemd/system/$app.target"
ynh_backup "/etc/systemd/system/${app}-front.service"
ynh_backup "/etc/systemd/system/${app}-back.service"

#=================================================
# BACKUP THE POSTGRES DATABASE
#=================================================
ynh_print_info "Backing up the POSTGRES database..."

ynh_psql_dump_db > db.sql

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
